add histogram LGDO
legend-exp/legend-pydataobj pull request #98
Opened 2024-07-10 08:34 UTC by ManuelHu

This is still a draft, I will create additional tests :-)

Some open questions:
* this currently has a hard import on the `hist` package, which could also be a strictly optional dependency. see also #48 
* I added an error message when trying to write a histogram with any `wo_mode` that might append. I am unsure if this is the nice way to do it...
* generally, having a base class for `Struct, but without a clear way for the user to add/remove fields` would make sense. This would affect the `Histogram{,Binning,Axes}` types, as all those have a fixed datatype in the spec and should not be user-modifiable?
   At least for `Histogram`, not being able to add/remove fields is a hard requirement - otherwise it cannot be read back as a histogram.

fixes #15

2024-07-11 09:48 UTC, gipert commented
Looks great Manuel! Some comments:

- we should also support variable-binning histograms
- I would ignore the "problem" with mutable `Struct`s for now 
- I think going for `lgdo.types.Histogram.Axis` is a good idea
- could you document a bit better if data is copied or actually viewed?

@oschulz:

- https://legend-exp.github.io/legend-data-format-specs/dev/hdf5/#Histograms does not mention histograms with variable binning, but should be straightforward to have `binedges` as an `array<1>{real}`.
- could you provide an LH5 file with a Histogram object serialized with Julia?

2024-07-11 09:48 UTC, gipert requested changes

2024-07-11 09:48 UTC, gipert commented on src/lgdo/types/histogram.py
> +                msg = "flow bins of hist.Hist cannopt be represented"
```suggestion
                msg = "flow bins of hist.Hist cannot be represented"
```

2024-07-11 12:03 UTC, ManuelHu commented
* conversion `hist.Hist` -> `np.ndarray` is (mostly) zero-copy
* conversion `np.ndarray/Histogram` -> `hist.Hist` (i.e. in `view_as("hist")` is _not_ just a view, but performs a full copy! Unfortunately there is no way to change it: https://github.com/scikit-hep/boost-histogram/issues/421

2024-07-11 14:54 UTC, oschulz commented
> https://legend-exp.github.io/legend-data-format-specs/dev/hdf5/#Histograms does not mention histograms with variable binning, but should be straightforward to have binedges as an array<1>{real}.

Yes, we should absolutely allow that.

> could you provide an LH5 file with a Histogram object serialized with Julia?

I'll add a test file to legend-testdata, give me a few days ...

2024-07-11 22:01 UTC, ManuelHu commented
Variable binning works now (with `array<1>{real}` as `binedges`). I can also prepare a PR to the data specification in the next days.
There is also some logic that converts an edge array to a range object, if this is possible (i.e. it has a uniform binning). I Am not sure if we want to keep that behavior...

but please do not merge yet, I still have one change in mind. I still want to change one possible parameter type of the binning, as now it is not so nice.

2024-07-12 15:31 UTC, oschulz commented
> I can also prepare a PR to the data specification in the next days.

Can you also add a test file to the legend-testdata repo via a PR there, so we can test on the Julia side before we merge here and on legend-testdata?

2024-07-13 10:40 UTC, ManuelHu commented
@oschulz see https://github.com/legend-exp/legend-testdata/pull/18
I now uploaded a test file with two 2D histograms, one with range axes, and one with variable binned axes.

2024-08-12 10:19 UTC, gipert requested changes

2024-08-12 10:19 UTC, gipert commented on src/lgdo/types/histogram.py
> +        weights: hist.Hist | np.ndarray,
```suggestion
        weights: hist.Hist | NDArray,
```

we should use more generic types in function signatures (see [remarks here](https://learn.scientific-python.org/development/guides/mypy/#tips-for-good-types)). Could you quickly go through all your function signatures and fix this?

2024-08-12 13:22 UTC, gipert commented
This PR seems good to go from my point of view, anything else @ManuelHu?

2024-08-12 13:56 UTC, ManuelHu commented
I also think it is ready, no particularly missing things come to my mind.

2024-08-12 14:04 UTC, merged